name: Emmy Debugger Core

on: [push]

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-2016
    steps:
    - uses: actions/checkout@v1
    
    - name: Build x86
      run: |
        mkdir x86
        cd x86
        cmake ../
        cmake --build . --config RelWithDebInfo --target install
    
    - name: Upload x86
      uses: actions/upload-artifact@v1.0.0
      with:
        name: x86
        path: x86/install/bin

    - name: Build x64
      run: |
        mkdir x64
        cd x64
        cmake ../ -G "Visual Studio 15 2017 Win64"
        cmake --build . --config RelWithDebInfo --target install
    
    - name: Upload x64
      uses: actions/upload-artifact@v1.0.0
      with:
        name: x64
        path: x64/install/bin

  build-darwin:
    name: Build Darwin
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1

    - name: Build
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ../
        make install
    
    - name: Upload
      uses: actions/upload-artifact@v1.0.0
      with:
        name: emmy_core.dylib
        path: build/install/bin/emmy_core.dylib

  build-linux:
    name: Build Linux
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1

    - name: Install
      run: |
        sudo apt-get install libreadline-dev

    - name: Build
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ../
        make install
    
    - name: Upload
      uses: actions/upload-artifact@v1.0.0
      with:
        name: emmy_core.so
        path: build/install/bin/emmy_core.so

  upload-release:
    name: Upload Release
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build-windows, build-darwin, build-linux]
    runs-on: [ubuntu-18.04]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@master
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ github.ref }}
          draft: true
          prerelease: true
      
      - name: Download Windows-x86
        uses: actions/download-artifact@v1.0.0
        with:
          name: x86
          path: artifact/x86
      
      - name: Zip x86
        uses: TheDoctor0/zip-release@v0.2.1
        with:
          filename: emmy_core@x86.zip
          path: artifact/x86
      
      - name: Upload x86
        uses: actions/upload-release-asset@v1.0.1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: emmy_core@x86.zip
          asset_name: emmy_core@x86.zip
          asset_content_type: application/tar+gzip
      
      - name: Download Windows-x64
        uses: actions/download-artifact@v1.0.0
        with:
          name: x64
          path: artifact/x64
      
      - name: Zip x64
        uses: TheDoctor0/zip-release@v0.2.1
        with:
          filename: emmy_core@x64.zip
          path: artifact/x64
      
      - name: Upload x64
        uses: actions/upload-release-asset@v1.0.1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: emmy_core@x64.zip
          asset_name: emmy_core@x64.zip
          asset_content_type: application/tar+gzip
          
      - name: Download so
        uses: actions/download-artifact@v1.0.0
        with:
          name: emmy_core.so
          path: artifact
      
      - name: Upload so
        uses: actions/upload-release-asset@v1.0.1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifact/emmy_core.so
          asset_name: emmy_core.so
          asset_content_type: application/gzip
      
      - name: Download dylib
        uses: actions/download-artifact@v1.0.0
        with:
          name: emmy_core.dylib
          path: artifact
      
      - name: Upload dylib
        uses: actions/upload-release-asset@v1.0.1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifact/emmy_core.dylib
          asset_name: emmy_core.dylib
          asset_content_type: application/gzip
